name: Create Git Tag

on:
  workflow_run:
    workflows: Flutter CI/CD  # Specify the name of your workflow

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Git Tag
        run: |
          git config user.email "hicli0001@gmail.com"
          git config user.name "TWIMM"
          git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Tag for release"
          git push origin --tags
